In [1]:
# Simple Split with Equal Sections

import numpy as np

# Create a 6x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]])
print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Split the array into 3 equal parts
result = np.vsplit(arr, 3)

print("\n The result of vsplit is:\n",result)

print("\nOutput Arrays:")
for i, part in enumerate(result):
    print(f"Part {i + 1}:\n{part}")
    print("Shape:", part.shape,"\n")

Input Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Shape: (6, 3)

 The result of vsplit is:
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]

Output Arrays:
Part 1:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3) 

Part 2:
[[ 7  8  9]
 [10 11 12]]
Shape: (2, 3) 

Part 3:
[[13 14 15]
 [16 17 18]]
Shape: (2, 3) 



In [2]:
# Simple Split with Equal Sections

import numpy as np

# Create a 6x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]])
print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Split the array into 4 equal parts
result = np.vsplit(arr, 4)

print("\n The result of vsplit is:\n",result)

Input Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Shape: (6, 3)


ValueError: array split does not result in an equal division

In [4]:
# Splitting with Specified Indices

# Input Array
print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Split the array at indices 2 and 4
result = np.vsplit(arr, [1, 2, 4])
print("\n The result of vsplit is:\n",result)

print("\nOutput Arrays:")
for i, part in enumerate(result):
    print(f"Part {i + 1}:\n{part}")
    print("Shape:", part.shape,"\n")


Input Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Shape: (6, 3)

 The result of vsplit is:
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]

Output Arrays:
Part 1:
[[1 2 3]]
Shape: (1, 3) 

Part 2:
[[4 5 6]]
Shape: (1, 3) 

Part 3:
[[ 7  8  9]
 [10 11 12]]
Shape: (2, 3) 

Part 4:
[[13 14 15]
 [16 17 18]]
Shape: (2, 3) 



In [5]:
# Using vsplit() on a 1D Array (Error Case)

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print("Input Array (1D):")
print(arr_1d)
print("Shape:", arr_1d.shape)

# Attempt to split
try:
    result = np.vsplit(arr_1d, 3)
except ValueError as e:
    print("\nError:", e)

Input Array (1D):
[1 2 3 4 5 6]
Shape: (6,)

Error: vsplit only works on arrays of 2 or more dimensions


In [8]:
# Splitting with Unequal Parts Using Indices

# Create a 4x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])
print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Split the array into unequal parts
result = np.vsplit(arr, [1, 3])
print("\n The result of vsplit is:\n",result)

print("\nOutput Arrays:")
for i, part in enumerate(result):
    print(f"Part {i + 1}:\n{part}")
    print("Shape:", part.shape,"\n")

Input Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)

 The result of vsplit is:
 [array([[1, 2, 3]]), array([[4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12]])]

Output Arrays:
Part 1:
[[1 2 3]]
Shape: (1, 3) 

Part 2:
[[4 5 6]
 [7 8 9]]
Shape: (2, 3) 

Part 3:
[[10 11 12]]
Shape: (1, 3) 



In [9]:
# Handling Split Errors

# Create a 2x2 array
arr = np.array([[1, 2],
                [3, 4]])
print("Input Array:")
print(arr)
print("Shape:", arr.shape)


result = np.vsplit(arr, 3)

# Attempt to split into 3 parts
try:
    result = np.vsplit(arr, 3)
except ValueError as e:
    print("\nError:", e)


Input Array:
[[1 2]
 [3 4]]
Shape: (2, 2)


ValueError: array split does not result in an equal division

In [10]:
# Simple Split with Equal Sections

import numpy as np

# Create a 4x6 array
arr = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12],
                [13, 14, 15, 16, 17, 18],
                [19, 20, 21, 22, 23, 24]])
print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Split the array into 3 equal parts
result = np.hsplit(arr, 3)
print("\n The result of hsplit is:\n",result)

print("\nOutput Arrays:")
for i, part in enumerate(result):
    print(f"Part {i + 1}:\n{part}")
    print("Shape:", part.shape,"\n")


Input Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

 The result of hsplit is:
 [array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]

Output Arrays:
Part 1:
[[ 1  2]
 [ 7  8]
 [13 14]
 [19 20]]
Shape: (4, 2) 

Part 2:
[[ 3  4]
 [ 9 10]
 [15 16]
 [21 22]]
Shape: (4, 2) 

Part 3:
[[ 5  6]
 [11 12]
 [17 18]
 [23 24]]
Shape: (4, 2) 



In [11]:
import numpy as np

# Create a 4x6 array
arr = np.array([[1, 2, 3, 4, 5, 6],
                [7, 8, 9, 10, 11, 12],
                [13, 14, 15, 16, 17, 18],
                [19, 20, 21, 22, 23, 24]])
print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Split the array into 4 equal parts
result = np.hsplit(arr, 4)
print("\n The result of hsplit is:\n",result)

Input Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)


ValueError: array split does not result in an equal division

In [12]:
# Splitting with Specified Indices

# Input Array
print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Split the array at indices 2 and 4
result = np.hsplit(arr, [1, 3, 4])
print("\n The result of hsplit is:\n",result)

print("\nOutput Arrays:")
for i, part in enumerate(result):
    print(f"Part {i + 1}:\n{part}")
    print("Shape:", part.shape)

Input Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

 The result of hsplit is:
 [array([[ 1],
       [ 7],
       [13],
       [19]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]]), array([[ 4],
       [10],
       [16],
       [22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]

Output Arrays:
Part 1:
[[ 1]
 [ 7]
 [13]
 [19]]
Shape: (4, 1)
Part 2:
[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]]
Shape: (4, 2)
Part 3:
[[ 4]
 [10]
 [16]
 [22]]
Shape: (4, 1)
Part 4:
[[ 5  6]
 [11 12]
 [17 18]
 [23 24]]
Shape: (4, 2)


In [13]:
#  Using hsplit() on a 1D Array
arr_1d = np.array([1, 2, 3, 4, 5, 6])
print("Input Array (1D):")
print(arr_1d)
print("Shape:", arr_1d.shape)

# Split the 1D array into 3 equal parts
result = np.hsplit(arr_1d, 3)
print("\n The result of hsplit is:\n",result)

print("\nOutput Arrays:")
for i, part in enumerate(result):
    print(f"Part {i + 1}:\n{part}")
    print("Shape:", part.shape,"\n")


Input Array (1D):
[1 2 3 4 5 6]
Shape: (6,)

 The result of hsplit is:
 [array([1, 2]), array([3, 4]), array([5, 6])]

Output Arrays:
Part 1:
[1 2]
Shape: (2,) 

Part 2:
[3 4]
Shape: (2,) 

Part 3:
[5 6]
Shape: (2,) 



In [15]:
# Splitting with Unequal Parts Using Indices
# Split the array into unequal parts

print("Input array:\n",arr)
result = np.hsplit(arr, [1, 5])
print("\nOutput Arrays:")
for i, part in enumerate(result):
    print(f"Part {i + 1}:\n{part}","\n")
    print("Shape:", part.shape)


Input array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Output Arrays:
Part 1:
[[ 1]
 [ 7]
 [13]
 [19]] 

Shape: (4, 1)
Part 2:
[[ 2  3  4  5]
 [ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]] 

Shape: (4, 4)
Part 3:
[[ 6]
 [12]
 [18]
 [24]] 

Shape: (4, 1)


In [17]:
# Handling Split Errors
print("Input array:\n",arr)

# Attempt to split into 4 parts
try:
    result = np.hsplit(arr, 4)
except ValueError as e:
    print("Error:", e)

Input array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Error: array split does not result in an equal division
