In [71]:
import numpy as np

# Input arrays
a = np.array([1, 2, 3])  # 1D array
b = np.array([4, 5, 6])  # 1D array

c = np.array([[1, 2], [3, 4]])  # 2D array
d = np.array([[5, 6], [7, 8]])  # 2D array

# Print the arrays and their shapes
print("Array a:\n", a)
print("Shape of a:", a.shape)
print("\nArray b:\n", b)
print("Shape of b:", b.shape)
print("\nArray c:\n", c)
print("Shape of c:", c.shape)
print("\nArray d:\n", d)
print("Shape of d:", d.shape)

Array a:
 [1 2 3]
Shape of a: (3,)

Array b:
 [4 5 6]
Shape of b: (3,)

Array c:
 [[1 2]
 [3 4]]
Shape of c: (2, 2)

Array d:
 [[5 6]
 [7 8]]
Shape of d: (2, 2)


In [74]:
print("Array a:\n", a)
print("Shape of a:", a.shape)
print("\nArray b:\n", b)
print("Shape of b:", b.shape)

result_1d = np.concatenate((a, b), axis=1)
print("\nconcatenate 1D arrays (a, b):")
print(result_1d)
print("Shape:", result_1d.shape)

Array a:
 [1 2 3]
Shape of a: (3,)

Array b:
 [4 5 6]
Shape of b: (3,)


AxisError: axis 1 is out of bounds for array of dimension 1

In [60]:
print("Array c:\n", c)
print("Shape of c:", c.shape)
print("\nArray d:\n", d)
print("Shape of d:", d.shape)

result_2d_axis0 = np.concatenate((c, d), axis=0)
print("\nconcatenate 2D arrays (c, d) along axis 0:")
print(result_2d_axis0)
print("Shape:", result_2d_axis0.shape)

Array c:
 [[1 2]
 [3 4]]
Shape of c: (2, 2)

Array d:
 [[5 6]
 [7 8]]
Shape of d: (2, 2)

concatenate 2D arrays (c, d) along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape: (4, 2)


In [61]:
print("Array c:\n", c)
print("Shape of c:", c.shape)
print("\nArray d:\n", d)
print("Shape of d:", d.shape)

result_2d_axis1 = np.concatenate((c, d), axis=1)
print("concatenate 2D arrays (c, d) along axis 1:")
print(result_2d_axis1)
print("Shape:", result_2d_axis1.shape)

Array c:
 [[1 2]
 [3 4]]
Shape of c: (2, 2)

Array d:
 [[5 6]
 [7 8]]
Shape of d: (2, 2)
concatenate 2D arrays (c, d) along axis 1:
[[1 2 5 6]
 [3 4 7 8]]
Shape: (2, 4)


In [62]:
print("Array a:\n", a)
print("Shape of a:", a.shape)
print("\nArray b:\n", b)
print("Shape of b:", b.shape)

result_stack_1d = np.stack((a, b), axis=0)
print("\nstack 1D arrays (a, b) along a new axis:")
print(result_stack_1d)
print("Shape:", result_stack_1d.shape)


Array a:
 [1 2 3]
Shape of a: (3,)

Array b:
 [4 5 6]
Shape of b: (3,)

stack 1D arrays (a, b) along a new axis:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [63]:
print("Array a:\n", a)
print("Shape of a:", a.shape)
print("\nArray b:\n", b)
print("Shape of b:", b.shape)

result_stack_1d = np.stack((a, b), axis=1)
print("\nstack 1D arrays (a, b) along a new axis:")
print(result_stack_1d)
print("Shape:", result_stack_1d.shape)

Array a:
 [1 2 3]
Shape of a: (3,)

Array b:
 [4 5 6]
Shape of b: (3,)

stack 1D arrays (a, b) along a new axis:
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


In [64]:
print("Array a:\n", a)
print("Shape of a:", a.shape)
print("\nArray b:\n", b)
print("Shape of b:", b.shape)

result_stack_1d = np.stack((a, b), axis=2)
print("\nstack 1D arrays (a, b) along a new axis:")
print(result_stack_1d)
print("Shape:", result_stack_1d.shape)

Array a:
 [1 2 3]
Shape of a: (3,)

Array b:
 [4 5 6]
Shape of b: (3,)


AxisError: axis 2 is out of bounds for array of dimension 2

In [ ]:


result_stack_1d = np.stack((a, b), axis=2)
print("\nstack 1D arrays (a, b) along a new axis:")
print(result_stack_1d)
print("Shape:", result_stack_1d.shape)

In [ ]:
np.stack((c, d), axis=2)
print("\n Result:\n",np.stack((c, d), axis=2))
print("\n Shape:",np.shape(np.stack((c, d), axis=2)))

In [ ]:
print("Array a:\n", a)
print("Shape of a:", a.shape)
print("\nArray b:\n", b)
print("Shape of b:", b.shape)

result_vstack_1d = np.vstack((a, b))
print("\nvstack 1D arrays (a, b):")
print(result_vstack_1d)
print("Shape:", result_vstack_1d.shape)


In [ ]:
print("Array c:\n", c)
print("Shape of c:", c.shape)
print("\nArray d:\n", d)
print("Shape of d:", d.shape)

result_vstack_2d = np.vstack((c, d))
print("\nvstack 2D arrays (c, d):")
print(result_vstack_2d)
print("Shape:", result_vstack_2d.shape)


In [65]:
print("Array a:\n", a)
print("Shape of a:", a.shape)
print("\nArray b:\n", b)
print("Shape of b:", b.shape)

result_hstack_1d = np.hstack((a, b))
print("\nhstack 1D arrays (a, b):")
print(result_hstack_1d)
print("Shape:", result_hstack_1d.shape)


Array a:
 [1 2 3]
Shape of a: (3,)

Array b:
 [4 5 6]
Shape of b: (3,)

hstack 1D arrays (a, b):
[1 2 3 4 5 6]
Shape: (6,)


In [66]:
print("Array c:\n", c)
print("Shape of c:", c.shape)
print("\nArray d:\n", d)
print("Shape of d:", d.shape)

result_hstack_2d = np.hstack((c, d))
print("\nhstack 2D arrays (c, d):")
print(result_hstack_2d)
print("Shape:", result_hstack_2d.shape)

Array c:
 [[1 2]
 [3 4]]
Shape of c: (2, 2)

Array d:
 [[5 6]
 [7 8]]
Shape of d: (2, 2)

hstack 2D arrays (c, d):
[[1 2 5 6]
 [3 4 7 8]]
Shape: (2, 4)


In [67]:
np.dstack((a, b))
print("\n Result:\n",np.dstack((a, b)))
print("\n Shape:",np.shape(np.dstack((a, b))))


 Result:
 [[[1 4]
  [2 5]
  [3 6]]]

 Shape: (1, 3, 2)


In [68]:
np.dstack((c, d))
print("\n Result:\n",np.dstack((c, d)))
print("\n Shape:",np.shape(np.dstack((c, d))))


 Result:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]

 Shape: (2, 2, 2)


In [69]:
np.column_stack((a, b))
print("\n Result:\n",np.column_stack((a, b)))
print("\n Shape:",np.shape(np.column_stack((a, b))))


 Result:
 [[1 4]
 [2 5]
 [3 6]]

 Shape: (3, 2)


In [70]:
np.column_stack((c, d))
print("\n Result:\n",np.column_stack((c, d)))
print("\n Shape:",np.shape(np.column_stack((c, d))))


 Result:
 [[1 2 5 6]
 [3 4 7 8]]

 Shape: (2, 4)
