# Euler’s number (ℯ) is approximately 2.718, and it’s the base of natural logarithms. It’s widely used in exponential growth, probability theory, and calculus.

Used in finance and biology for compound interest and bacterial growth.

In [1]:
# Calculating Exponential Growth

import numpy as np

# Population Growth Formula: P(t) = P0 * e^(rt)
P0 = 1000  # Initial population
r = 0.05   # Growth rate
t = 10     # Time in years

future_population = P0 * np.e ** (r * t)

print(f"Future population after {t} years: {future_population:.2f}")

Future population after 10 years: 1648.72


In [5]:
# Probability & Machine Learning (Softmax Activation)

scores = np.array([9.0, 7.0, 15.0])

softmax = np.exp(scores) / np.sum(np.exp(scores))

print(softmax)

[2.47179601e-03 3.34521213e-04 9.97193683e-01]


In [6]:
np.sum(softmax)

np.float64(1.0)

# Euler's constant (γ ≈ 0.577) appears in calculus, number theory, and harmonic series.

In [7]:
np.euler_gamma

0.5772156649015329

# Infinity Representation (∞)
numpy.inf represents positive infinity, commonly used in limits, optimization, and numerical comparisons.

In [8]:
# Handling Division by Zero

x = np.array([1, 2, 0, -3])

result = 1 / x

print(result)  # Output includes 'inf' where division by zero occurs

# Prevents crashes in numerical computations.

[ 1.          0.5                inf -0.33333333]


C:\Users\kautk\AppData\Local\Temp\ipykernel_36652\2186341755.py:5: RuntimeWarning: divide by zero encountered in divide
  result = 1 / x


In [10]:
np.inf == np.inf

True

In [11]:
# Comparing Values

x = np.array([10, 50, 100, np.inf])

print(np.isinf(x))  # Identifies infinite values

# Used in error handling and data validation.

[False False False  True]


In [13]:
# Finding the Minimum with inf Initialization

values = [100, 200, 50, 300]
min_val = np.inf

for v in values:
    if v < min_val:
        min_val = v

print(f"Minimum value: {min_val}")

Minimum value: 50


In [ ]:
# Used in pathfinding algorithms (e.g., Dijkstra’s algorithm).

# Not a Number (NaN)
numpy.nan represents invalid mathematical results, such as 0/0 or log(-1).

In [14]:
# Handling Undefined Operations
print(np.log(-1))  # Returns 'nan'

# Used in error handling and data science.

nan


C:\Users\kautk\AppData\Local\Temp\ipykernel_36652\3800388505.py:2: RuntimeWarning: invalid value encountered in log
  print(np.log(-1))  # Returns 'nan'


In [15]:
# Filtering Out NaN Values

data = np.array([10, np.nan, 30, np.nan, 50])

cleaned_data = data[~np.isnan(data)]

print(cleaned_data)

# Used in data cleaning.

[10. 30. 50.]


In [16]:
# Filling NaN Values

data = np.array([10, np.nan, 30, np.nan, 50])

data[np.isnan(data)] = np.mean(data[~np.isnan(data)])  # Replace NaN with mean
print(data)

# Used in machine learning preprocessing.

[10. 30. 30. 30. 50.]


In [20]:
np.nan == np.nan

False

# Pi (π)
π = 3.1415926535, used in geometry, physics, and engineering.

In [17]:
# Calculating Circle Area

r = 5
area = np.pi * r**2

print(f"Circle area: {area}")

Circle area: 78.53981633974483


In [18]:
np.pi

3.141592653589793

In [19]:
# Converting Degrees to Radians

degrees = np.array([0, 30, 45, 90, 180])

radians = degrees * (np.pi / 180)
print(radians)

[0.         0.52359878 0.78539816 1.57079633 3.14159265]


In [ ]:
# Used in engineering and physics.
# Used in trigonometry and machine learning.
# Used in signal processing.