In [1]:
# Inserting a Scalar Value into a Flattened Array

import numpy as np

# Create a 2D array
arr = np.arange(6).reshape(3, 2)
print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Insert value '6' at index 1 in the flattened array
result = np.insert(arr, 1, 6)
print("\nResult of Insertion in Flattened Array:")
print(result)
print("Shape:", result.shape)


Input Array:
[[0 1]
 [2 3]
 [4 5]]
Shape: (3, 2)

Result of Insertion in Flattened Array:
[0 6 1 2 3 4 5]
Shape: (7,)


In [5]:
# Inserting a Scalar Along a Specific Axis

print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Insert '6' along axis=1, before index 1
result = np.insert(arr, 1, 6, axis=1)
print("\nResult of Insertion Along Axis=1:")
print(result)
print("Shape:", result.shape)


Input Array:
[[0 1]
 [2 3]
 [4 5]]
Shape: (3, 2)

Result of Insertion Along Axis=1:
[[0 6 1]
 [2 6 3]
 [4 6 5]]
Shape: (3, 3)


In [3]:
#  Inserting Multiple Values with Advanced Indexing

print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Insert different values at the same index across rows
result = np.insert(arr, [1], [[7], [8], [9]], axis=1)
print("\nResult with Multiple Values at Index 1 Along Axis=1:")
print(result)
print("Shape:", result.shape)


Input Array:
[[0 1]
 [2 3]
 [4 5]]
Shape: (3, 2)

Result with Multiple Values at Index 1 Along Axis=1:
[[0 7 1]
 [2 8 3]
 [4 9 5]]
Shape: (3, 3)


In [6]:
# Using Slices for Insertion

print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Flatten the array and insert using a slice
arr_flattened = arr.flatten()
print("\nFlattened array:\n",arr_flattened)

result = np.insert(arr, slice(2, 4), [7, 8])
print("\nResult with Sliced Insertion in Flattened Array:")
print(result)
print("Shape:", result.shape)

Input Array:
[[0 1]
 [2 3]
 [4 5]]
Shape: (3, 2)

Flattened array:
 [0 1 2 3 4 5]

Result with Sliced Insertion in Flattened Array:
[0 1 7 2 8 3 4 5]
Shape: (8,)


In [7]:
# Delete an Element from a 1D Array

import numpy as np

# Define a 1D array
arr = np.array([1, 2, 3, 4, 5])
print("Original Array:")
print(arr)

# Delete the element at index 2
result = np.delete(arr, 2)
print("\nArray after deleting element at index 2:")
print(result)

Original Array:
[1 2 3 4 5]

Array after deleting element at index 2:
[1 2 4 5]


In [8]:
# Delete a Row from a 2D Array

# Define a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nOriginal 2D Array:")
print(arr)

# Delete the row at index 1
result = np.delete(arr, 1, axis=0)
print("\nArray after deleting row 1:")
print(result)



Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after deleting row 1:
[[1 2 3]
 [7 8 9]]


In [10]:
# Delete a Column from a 2D Array

print("\nOriginal 2D Array:")
print(arr)

# Delete the column at index 1
result = np.delete(arr, 0, axis=1)
print("\nArray after deleting column 1:")
print(result)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after deleting column 1:
[[2 3]
 [5 6]
 [8 9]]


In [11]:
# Delete Elements at Multiple Indices in a Flattened Array

# Define a 2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("\nOriginal 2D Array:")
print(arr)

arr_flattened = arr.flatten()
print("\nFlattened array:\n",arr_flattened)

# Delete elements at indices 1, 3, and 5 from the flattened array
result = np.delete(arr, [1, 3, 5], axis=None)
print("\nArray after deleting multiple indices (flattened):")
print(result)



Original 2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Array after deleting multiple indices (flattened):
[ 1  3  5  7  8  9 10 11 12]


In [12]:
#  Using Boolean Masking for Deletion

# Instead of using numpy.delete(), you can also use a boolean mask to selectively keep elements in the array.

# Define a 1D array
arr = np.arange(12)
print("\nOriginal Array:")
print(arr)

# Create a mask to delete elements at indices 0, 2, and 4
mask = np.ones(len(arr), dtype=bool)
print("\nmask:\n",mask)

mask[[0, 2, 4]] = False
print("\nmask:\n",mask)

result = arr[mask]
print("\nArray after applying boolean mask to delete elements at indices 0, 2, and 4:")
print(result)


Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

mask:
 [ True  True  True  True  True  True  True  True  True  True  True  True]

mask:
 [False  True False  True False  True  True  True  True  True  True  True]

Array after applying boolean mask to delete elements at indices 0, 2, and 4:
[ 1  3  5  6  7  8  9 10 11]
