In [1]:
# Append Values to a 1D Array

import numpy as np

# Define a 1D array
arr = np.array([1, 2, 3])
print("Original Array:")
print(arr)

# Append a new sequence to the array
result = np.append(arr, [4, 5, 6])
print("\nArray after appending [4, 5, 6]:")
print(result)

Original Array:
[1 2 3]

Array after appending [4, 5, 6]:
[1 2 3 4 5 6]


In [2]:
# Append Rows to a 2D Array (Along Axis 0)

# Define a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal 2D Array:")
print(arr)

# Append a new row
result = np.append(arr, [[7, 8, 9]], axis=0)
print("\nArray after appending a new row [7, 8, 9] along axis 0:")
print(result)



Original 2D Array:
[[1 2 3]
 [4 5 6]]

Array after appending a new row [7, 8, 9] along axis 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:


# Define a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal 2D Array:")
print(arr)

# Append a new row
result = np.append(arr, [[7, 8, 9, 10]], axis=0)
print("\nArray after appending a new row [7, 8, 9, 10] along axis 0:")
print(result)



Original 2D Array:
[[1 2 3]
 [4 5 6]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

In [6]:
# Append Columns to a 2D Array (Along Axis 1)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal 2D Array:")
print(arr)

# Append a new column
result = np.append(arr, [[7], [8]], axis=1)
print("\nArray after appending a new column [7, 8] along axis 1:")
print(result)


Original 2D Array:
[[1 2 3]
 [4 5 6]]

Array after appending a new column [7, 8] along axis 1:
[[1 2 3 7]
 [4 5 6 8]]


In [8]:
# Flatten and Append to a 2D Array

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal 2D Array:")
print(arr)

# Append with axis=None (flattened)
result = np.append(arr, [7, 8, 9], axis=None)
print("\nArray after appending [7, 8, 9] with axis=None (flattened):")
print(result)



Original 2D Array:
[[1 2 3]
 [4 5 6]]

Array after appending [7, 8, 9] with axis=None (flattened):
[1 2 3 4 5 6 7 8 9]


In [9]:
# Handling Shape Mismatches

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOriginal 2D Array:")
print(arr)


try:
    # Attempt to append a 1D array as a row in a 2D array
    result = np.append(arr, [7, 8, 9], axis=0)
except ValueError as e:
    print("\nError encountered:", e)



Original 2D Array:
[[1 2 3]
 [4 5 6]]

Error encountered: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [10]:
# Resize a 1D Array to a Larger Size

import numpy as np

# Define a 1D array
arr = np.array([1, 2, 3])
print("Original Array:")
print(arr)
print("Original Shape:", arr.shape)

# Resize to a larger shape
result = np.resize(arr, 6)
print("\nResized Array:")
print(result)
print("Resized Shape:", result.shape)

Original Array:
[1 2 3]
Original Shape: (3,)

Resized Array:
[1 2 3 1 2 3]
Resized Shape: (6,)


In [11]:
#  Resize a 2D Array to Add Columns
# Define a 2D array
arr = np.array([[1, 2], [3, 4]])
print("Original 2D Array:")
print(arr)
print("Original Shape:", arr.shape)

# Resize to a new shape with additional columns
result = np.resize(arr, (2, 4))
print("\nResized Array:")
print(result)
print("Resized Shape:", result.shape)

# Resize to a new shape with additional rows
result = np.resize(arr, (4, 2))
print("\nResized Array:")
print(result)
print("Resized Shape:", result.shape)

Original 2D Array:
[[1 2]
 [3 4]]
Original Shape: (2, 2)

Resized Array:
[[1 2 3 4]
 [1 2 3 4]]
Resized Shape: (2, 4)

Resized Array:
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
Resized Shape: (4, 2)


In [12]:
# Resize to a Smaller Shape

print("Original 2D Array:")
print(arr)
print("Original Shape:", arr.shape)

# Resize to a smaller shape
result = np.resize(arr, (1, 3))
print("\nResized Array:")
print(result)
print("Resized Shape:", result.shape)


Original 2D Array:
[[1 2]
 [3 4]]
Original Shape: (2, 2)

Resized Array:
[[1 2 3]]
Resized Shape: (1, 3)


In [13]:
#  Resizing a 2D Array to a Larger Shape with More Rows

print("Original 2D Array:")
print(arr)
print("Original Shape:", arr.shape)

# Resize with additional rows
result = np.resize(arr, (3, 2))
print("\nResized Array:")
print(result)
print("Resized Shape:", result.shape)


Original 2D Array:
[[1 2]
 [3 4]]
Original Shape: (2, 2)

Resized Array:
[[1 2]
 [3 4]
 [1 2]]
Resized Shape: (3, 2)


In [14]:
# Resize to a single row with more elements

print("Original 2D Array:")
print(arr)
print("Original Shape:", arr.shape)

result = np.resize(arr, (1, 6))
print("\nResized Array (Single Row):")
print(result)
print("Resized Shape:", result.shape)


Original 2D Array:
[[1 2]
 [3 4]]
Original Shape: (2, 2)

Resized Array (Single Row):
[[1 2 3 4 1 2]]
Resized Shape: (1, 6)


In [15]:
# Resize to a single column with more elements

print("Original 2D Array:")
print(arr)
print("Original Shape:", arr.shape)

result = np.resize(arr, (6, 1))
print("\nResized Array (Single Column):")
print(result)
print("Resized Shape:", result.shape)

Original 2D Array:
[[1 2]
 [3 4]]
Original Shape: (2, 2)

Resized Array (Single Column):
[[1]
 [2]
 [3]
 [4]
 [1]
 [2]]
Resized Shape: (6, 1)
