In [2]:
# Constant Padding

import numpy as np

a = [1, 2, 3, 4, 5]
print("List:\n",a)
result = np.pad(a, (2, 3), mode='constant', constant_values=(4, 6))

print(result)
print(type(a))
print(type(result))

List:
 [1, 2, 3, 4, 5]
[4 4 1 2 3 4 5 6 6 6]
<class 'list'>
<class 'numpy.ndarray'>


In [3]:
# Constant Padding

import numpy as np

a = np.array([1, 2, 3, 4, 5])
result = np.pad(a, (2, 3), mode='constant', constant_values=(4, 6))
print(result)
print(type(a))
print(type(result))

[4 4 1 2 3 4 5 6 6 6]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
# Edge Padding
a = [1, 2, 3, 4, 5]
result = np.pad(a, (2, 3), mode='edge')
print(result)

[1 1 1 2 3 4 5 5 5 5]


In [6]:
# Reflect Padding

a = [1, 2, 3, 4, 5]
result = np.pad(a, (4, 3), mode='reflect')
print(result)

[5 4 3 2 1 2 3 4 5 4 3 2]


In [7]:
# Symmetric Padding

a = [1, 2, 3, 4, 5]
result = np.pad(a, (2, 3), mode='symmetric')
print(result)

[2 1 1 2 3 4 5 5 4 3]


In [10]:
# maximum Padding

a = [1, 2, 5, 4, 3]
result = np.pad(a, (2, 3), mode='mean')
print(result)

[3 3 1 2 5 4 3 3 3 3]
