In [2]:
import numpy as np

In [2]:
m = np.array(3)
m

array(3)

In [3]:
m.ndim

0

In [4]:
m.shape

()

In [5]:
m.dtype

dtype('int32')

In [6]:
a = np.array(1,2)
a

TypeError: Cannot interpret '2' as a data type

In [8]:
a = np.array([1,2])
a

array([1, 2])

In [9]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [10]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [12]:
a.ndim

1

In [13]:
a.shape

(5,)

In [14]:
a.dtype

dtype('int32')

In [15]:
b.dtype

dtype('int32')

In [16]:
a

array([1, 2, 3, 4, 5])

In [18]:
b

array([1, 2, 3, 4, 5])

In [19]:
a + b

array([ 2,  4,  6,  8, 10])

In [20]:
a*b

array([ 1,  4,  9, 16, 25])

In [21]:
a-b

array([0, 0, 0, 0, 0])

In [22]:
a/b

array([1., 1., 1., 1., 1.])

In [24]:
v = np.array([[1,2,3],[4,5,6]])
v

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
v.ndim

2

In [26]:
v.shape

(2, 3)

In [27]:
s = np.array([[1,2,3],[4,5,6],[9,8,7]])
s

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7]])

In [28]:
s.ndim

2

In [29]:
s.shape

(3, 3)

In [30]:
s.dtype

dtype('int32')

In [35]:
l = np.zeros(5)
l

array([0., 0., 0., 0., 0.])

In [36]:
l.shape

(5,)

In [37]:
l.ndim

1

In [38]:
l.dtype

dtype('float64')

In [43]:
k= np.zeros([5,3])
k

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
k.ndim

2

In [45]:
k.shape

(5, 3)

In [46]:
k.dtype

dtype('float64')

In [53]:
o = np.zeros(5,dtype=int)
o

array([0, 0, 0, 0, 0])

In [54]:
o.dtype

dtype('int32')

In [55]:
np.zeros(5, float)

array([0., 0., 0., 0., 0.])

In [58]:
c = np.zeros([5,5],complex)
c

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [59]:
c.dtype

dtype('complex128')

In [61]:
p = np.zeros([5,2,3],int)
p

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [62]:
p.ndim

3

In [63]:
p.shape

(5, 2, 3)

In [64]:
p.dtype

dtype('int32')

In [65]:
np.zeros([5,5],int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [67]:
d = np.ones(7,int)
d

array([1, 1, 1, 1, 1, 1, 1])

In [68]:
d.dtype

dtype('int32')

In [69]:
e = np.ones(7,float)
e

array([1., 1., 1., 1., 1., 1., 1.])

In [70]:
e.dtype

dtype('float64')

In [71]:
e = np.zeros(shape=(3,5))
e

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
f = np.zeros(shape=(3,5,2))
f

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [76]:
g = np.zeros(shape=(2,3,4),dtype=int)
g

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [77]:
g.ndim

3

In [78]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [ ]:
np.array([1, 2, 3], dtype=complex)

In [ ]:
np.ones(5)

In [25]:
h = np.array([2,3])

In [26]:
h.sum()

5

In [27]:
h.sum(axis=0)

5

In [28]:
h.sum(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [30]:
h = np.array([[1,7],[3,6]])

In [31]:
h.ndim

2

In [34]:
h.shape

(2, 2)

In [21]:
h

array([[1, 7],
       [3, 6]])

In [22]:
h.sum()

17

In [23]:
h.sum(axis=0)

array([ 4, 13])

In [24]:
h.sum(axis=1)

array([8, 9])

In [46]:
h = np.array([[1,2],[3,4],[5,6]])

In [47]:
h

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
h.shape

(3, 2)

In [49]:
h.ndim

2

In [50]:
h.sum()

21

In [51]:
h.sum(axis=0)

array([ 9, 12])

In [52]:
h.sum(axis=1)

array([ 3,  7, 11])

In [53]:
h.sum(axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [55]:
h = np.array([[[1,2],[3,4],[5,6]]])

In [56]:
h.sum()

21

In [57]:
h.sum(axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
h.sum(axis=1)

array([[ 9, 12]])

In [59]:
h.sum(axis=2)

array([[ 3,  7, 11]])

In [70]:
h = np.array([[[1,2],[3,4],[5,6]],[[20,30],[40,50],[60,70]]])

In [82]:
h

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[20, 30],
        [40, 50],
        [60, 70]]])

In [72]:
h.ndim

3

In [83]:
h.size

12

In [73]:
h.shape

(2, 3, 2)

In [74]:
h.sum()

291

In [79]:
h

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[20, 30],
        [40, 50],
        [60, 70]]])

In [75]:
h.sum(axis=0)

array([[21, 32],
       [43, 54],
       [65, 76]])

In [76]:
h.sum(axis=1)

array([[  9,  12],
       [120, 150]])

In [80]:
h.sum(axis=2)

array([[  3,   7,  11],
       [ 50,  90, 130]])

In [81]:
h.sum(axis=3)

AxisError: axis 3 is out of bounds for array of dimension 3