# numpy.concatenate((array1, array2, ...), axis=0, out=None, dtype=None, casting='same_kind')


In [21]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

result = np.concatenate((arr1, arr2), axis=0)
print(result)


[[1 2]
 [3 4]
 [5 6]]


In [22]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

result = np.concatenate((arr1, arr2), axis=None)
print(result)


[1 2 3 4 5 6]


In [23]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

result = np.concatenate((arr1, arr2), axis=1)
print(result)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [24]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.concatenate((arr1, arr2), axis=1)
print(result)


[[1 2 5 6]
 [3 4 7 8]]


#  Specifying the out Parameter

In [25]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

out_array = np.zeros((3, 2))
print(out_array,"\n\n")

np.concatenate((arr1, arr2), axis=0, out=out_array)
print(out_array)


[[0. 0.]
 [0. 0.]
 [0. 0.]] 


[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [36]:
arr1 = np.array([1.2, 3.4])
arr2 = np.array([5, 6])

result = np.concatenate((arr1, arr2), dtype=np.int32, casting='unsafe')
print(result,"\n\n")

print(list(result))

[1 3 5 6] 


[1, 3, 5, 6]


# # Key Points to Remember:
axis defines how the arrays are concatenated (along rows, columns, or flattened).

out allows you to store the result in an existing array.

dtype and casting manage the data types of the resulting array.

# numpy.stack(arrays, axis=0, out=None, dtype=None, casting='same_kind')

In [29]:
# Stacking 1D Arrays Along a New Axis

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.stack((arr1, arr2), axis=0)
print(result)


[[1 2 3]
 [4 5 6]]


In [30]:
result = np.stack((arr1, arr2), axis=1)
print(result)


[[1 4]
 [2 5]
 [3 6]]


In [31]:
#Stacking 2D Arrays into a 3D Array

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.stack((arr1, arr2), axis=0)
print(result)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Stacking 2D Arrays Along a Different Axis
result = np.stack((arr1, arr2), axis=1)
print(result)


[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [32]:
# Using out Parameter for Output

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

out_array = np.zeros((2, 3))
print(out_array,"\n\n")

np.stack((arr1, arr2), axis=0, out=out_array)
print(out_array)


[[0. 0. 0.]
 [0. 0. 0.]] 


[[1. 2. 3.]
 [4. 5. 6.]]


In [33]:
# Using dtype and casting
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.array([4.0, 5.0, 6.0], dtype=np.float64)

result = np.stack((arr1, arr2), dtype=np.float64)
print(result)


[[1. 2. 3.]
 [4. 5. 6.]]


# Key Points to Remember
axis: Defines the axis along which to stack arrays, and a new axis is created along that dimension.

All arrays must have the same shape before stacking.

out: Allows you to store the stacked result in a pre-existing array, which must have the correct shape and dtype.

dtype and casting: Used for handling data types and conversions between different array types.