In [1]:
import numpy as np

array_from_list = np.array([1, 2, 3, 4, 5])
array_from_tuple = np.array((1, 2, 3, 4, 5))


In [2]:
array_from_list

array([1, 2, 3, 4, 5])

In [3]:
array_from_tuple

array([1, 2, 3, 4, 5])

In [4]:
zeros_array = np.zeros((3, 4))  # 3x4 array of zeros
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [7]:
np.zeros((3, 4, 2), dtype = int)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [8]:
ones_array = np.ones((2, 3))  # 2x3 array of ones
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.ones((4, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.identity(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
np.eye(3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.eye(3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [16]:
np.eye(3,k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [17]:
x = np.arange(6)

In [18]:
x

array([0, 1, 2, 3, 4, 5])

In [ ]:
x

In [19]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
np.linspace(0,10,2)

array([ 0., 10.])

In [25]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [26]:
np.linspace(0,10,num=4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [27]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.full(7,10)

array([10, 10, 10, 10, 10, 10, 10])

In [23]:
np.full((5,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [30]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])