In [4]:
# concatenate product names with their categories for reporting

import numpy as np

product_names = np.array(["Laptop", "Biscuit", "Smartphone"])
categories = np.array([" - Electronics", " - FMCG", " - Electronics"])

combined = np.strings.add(product_names, categories)
print(combined)

['Laptop - Electronics' 'Biscuit - FMCG' 'Smartphone - Electronics']


In [2]:
print(product_names + categories )

['Laptop - Electronics' 'Biscuit - FMCG' 'Smartphone - Electronics']


In [5]:
# concatenate product names with their categories for reporting

import numpy as np

product_names = np.array(["Laptop", "Biscuit", "Smartphone"])
categories = np.array([" - Electronics", " - FMCG"])
combined = np.strings.add(product_names, categories)
print(combined)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [6]:
# Add "Account Number: " as a prefix to account numbers

account_numbers = np.array(["12345", "67890", "54321"])
print(account_numbers)

prefix = np.array(["Account Number: "] * len(account_numbers))
print(prefix)

formatted = np.strings.add(prefix, account_numbers)
print(formatted)

['12345' '67890' '54321']
['Account Number: ' 'Account Number: ' 'Account Number: ']
['Account Number: 12345' 'Account Number: 67890' 'Account Number: 54321']


In [7]:
# Combine first and last names into full names

first_names = np.array(["Alice", "Bob", "Charlie"])
last_names = np.array(["Johnson", "Smith", "Brown"])
full_names = np.strings.add(first_names, " " + last_names)
print(full_names)

['Alice Johnson' 'Bob Smith' 'Charlie Brown']


In [8]:
print(first_names + " " + last_names)

['Alice Johnson' 'Bob Smith' 'Charlie Brown']


In [9]:
# Combine building codes and room numbers for identification

building_codes = np.array(["B1", "B2", "B3"])
room_numbers = np.array(["101", "202", "303"])

room_labels = building_codes + "-" + room_numbers
print(room_labels)

['B1-101' 'B2-202' 'B3-303']


In [10]:
# Combine directory paths with filenames to generate full file paths

directories = np.array(["/home/user/", "/home/user/", "/home/user/"])
filenames = np.array(["file1.txt", "file2.txt", "file3.txt"])

file_paths = np.strings.add(directories, filenames)
print(file_paths)

['/home/user/file1.txt' '/home/user/file2.txt' '/home/user/file3.txt']


In [11]:
# Apply concatenation conditionally

x1 = np.array(["Apple", "Banana", "Cherry"])
x2 = np.array([" Juice", " Smoothie", " Jam"])

condition = np.array([True, False, True])

result = np.strings.add(x1, x2, where=condition)
print(result)

# Concatenation happens only where the condition is True. Other elements remain unchanged.

['Apple Juice' '' 'Cherry Jam']


In [16]:
np.strings.add(1.0, 4.0)

np.float64(5.0)

In [17]:
a = np.array([2,3,4,5,6,7])
b = np.array([4,5,6,7,8,9])

print(a+b)

[ 6  8 10 12 14 16]


In [18]:
np.add(a, b)

array([ 6,  8, 10, 12, 14, 16])

In [19]:
# The + operator can be used as a shorthand for np.add on ndarrays.
x1 = np.arange(9.0).reshape((3, 3))
print("x1:\n",x1,"\n")

x2 = np.arange(3.0)
print("x2:\n",x2,"\n")

print("x1 + x2:\n", x1+x2)

x1:
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]] 

x2:
 [0. 1. 2.] 

x1 + x2:
 [[ 0.  2.  4.]
 [ 3.  5.  7.]
 [ 6.  8. 10.]]


In [20]:
print("x1 + x2:\n", np.add(x1, x2))

x1 + x2:
 [[ 0.  2.  4.]
 [ 3.  5.  7.]
 [ 6.  8. 10.]]


In [22]:
# Create repeated promotional messages based on item quantities

import numpy as np

products = np.array(["Buy One Get One Free! ", "Discount 20% ", "Limited Offer"])
repeat_count = np.array([2, 3, 1])

promotions = np.strings.multiply(products, repeat_count)
print(promotions)

['Buy One Get One Free! Buy One Get One Free! Buy One Get One Free! Buy One Get One Free! Buy One Get One Free! '
 'Discount 20% Discount 20% Discount 20% Discount 20% Discount 20% '
 'Limited OfferLimited OfferLimited OfferLimited OfferLimited Offer']


In [24]:
# Create a visual separator of dashes for account summaries

separator = np.array(["-"])
repeat_count = np.array([30])

formatted_separator = np.strings.multiply(separator, repeat_count)
print(formatted_separator)

['******************************']


In [25]:
# Repeat grade symbols for visual emphasis

grades = np.array(["A", "B", "C"])
repeat_count = np.array([5, 3, 2])

emphasized_grades = np.strings.multiply(grades, repeat_count)
print(emphasized_grades)

['AAAAA' 'BBB' 'CC']


In [26]:
# Generate repeated test strings for message loading

test_string = np.array(["LOADING_"])
repeat_count = np.array([10])

test_cases = np.strings.multiply(test_string, repeat_count)
print(test_cases)

['LOADING_LOADING_LOADING_LOADING_LOADING_LOADING_LOADING_LOADING_LOADING_LOADING_']


In [27]:
# Generate multiple copies of item labels

labels = np.array(["Item123 ", "Item456 "])
repeat_count = np.array([3, 2])

repeated_labels = np.strings.multiply(labels, repeat_count)
print(repeated_labels)

['Item123 Item123 Item123 ' 'Item456 Item456 ']


In [28]:
# When repeat_count is less than 0, the result is an empty string.

strings = np.array(["Negative", "Test"])
repeat_count = np.array([-1, 0])

result = np.strings.multiply(strings, repeat_count)
print(result)

['' '']


In [31]:
# Broadcasting with Scalars

strings = np.array(["Repeat ", "Fun "])
repeat_count = 5

result = np.strings.multiply(strings, repeat_count)
print(result)

# A scalar repeat_count is broadcasted to apply the same repetition to all strings.

['Repeat Repeat Repeat Repeat Repeat ' 'Fun Fun Fun Fun Fun ']


In [32]:
import numpy as np
arr = np.array(["a", "b", "c"])
np.strings.multiply(arr, 3)

array(['aaa', 'bbb', 'ccc'], dtype='<U3')

In [33]:
i = np.array([1, 2, 3])

np.strings.multiply(arr, i)

array(['a', 'bb', 'ccc'], dtype='<U3')

In [34]:
np.strings.multiply(np.array(['a']), i)

array(['a', 'aa', 'aaa'], dtype='<U3')

In [35]:
a = np.array(['a', 'b', 'c', 'd', 'e', 'f']).reshape((2, 3))

print(a)

np.strings.multiply(a, 3)

[['a' 'b' 'c']
 ['d' 'e' 'f']]


array([['aaa', 'bbb', 'ccc'],
       ['ddd', 'eee', 'fff']], dtype='<U3')

In [36]:
np.strings.multiply(a, i)

array([['a', 'bb', 'ccc'],
       ['d', 'ee', 'fff']], dtype='<U3')

In [37]:
# Using Broadcasting with Arrays

strings = np.array(["Header ", "Footer ", "Body "])
repeat_count = np.array([2, 3, 4])

result = np.strings.multiply(strings, repeat_count)
print(result)

['Header Header ' 'Footer Footer Footer ' 'Body Body Body Body ']
