In [1]:
# Simple Split with Equal Sections

import numpy as np

# Create a 3x3x6 array
arr = np.array([[[1, 2, 3, 4, 5, 6],
                 [7, 8, 9, 10, 11, 12],
                 [13, 14, 15, 16, 17, 18]],

                [[19, 20, 21, 22, 23, 24],
                 [25, 26, 27, 28, 29, 30],
                 [31, 32, 33, 34, 35, 36]],

                [[37, 38, 39, 40, 41, 42],
                 [43, 44, 45, 46, 47, 48],
                 [49, 50, 51, 52, 53, 54]]])

print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Split the array into 3 equal parts along the depth (3rd axis)
result = np.dsplit(arr, 3)
print("\n result:\n",result)

print("\nOutput Arrays:")
for i, part in enumerate(result):
    print(f"\nPart {i + 1}:\n{part}")
    print("Shape:", part.shape)

Input Array:
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]]

 [[19 20 21 22 23 24]
  [25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]
  [49 50 51 52 53 54]]]
Shape: (3, 3, 6)

 result:
 [array([[[ 1,  2],
        [ 7,  8],
        [13, 14]],

       [[19, 20],
        [25, 26],
        [31, 32]],

       [[37, 38],
        [43, 44],
        [49, 50]]]), array([[[ 3,  4],
        [ 9, 10],
        [15, 16]],

       [[21, 22],
        [27, 28],
        [33, 34]],

       [[39, 40],
        [45, 46],
        [51, 52]]]), array([[[ 5,  6],
        [11, 12],
        [17, 18]],

       [[23, 24],
        [29, 30],
        [35, 36]],

       [[41, 42],
        [47, 48],
        [53, 54]]])]

Output Arrays:

Part 1:
[[[ 1  2]
  [ 7  8]
  [13 14]]

 [[19 20]
  [25 26]
  [31 32]]

 [[37 38]
  [43 44]
  [49 50]]]
Shape: (3, 3, 2)

Part 2:
[[[ 3  4]
  [ 9 10]
  [15 16]]

 [[21 22]
  [27 28]
  [33 34]]

 [[39 40]
  [45 46]
  [51 52]]]
Shap

In [2]:
type(result)

list

In [3]:
# Split the array into 4 equal parts along the depth (3rd axis)

print("Input Array:")
print(arr)
print("Shape:", arr.shape)


result = np.dsplit(arr, 4)
print("\nOutput Arrays:")
for i, part in enumerate(result):
    print(f"\nPart {i + 1}:\n{part}")
    print("Shape:", part.shape)

Input Array:
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]]

 [[19 20 21 22 23 24]
  [25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]
  [49 50 51 52 53 54]]]
Shape: (3, 3, 6)


ValueError: array split does not result in an equal division

In [4]:
# Splitting with Specified Indices

print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Split the array at specified depth indices
result = np.dsplit(arr, [1, 3, 4])
print("\nOutput Arrays:")

for i, part in enumerate(result):
    print(f"\nPart {i + 1}:\n{part}")
    print("Shape:", part.shape)

Input Array:
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]]

 [[19 20 21 22 23 24]
  [25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]
  [49 50 51 52 53 54]]]
Shape: (3, 3, 6)

Output Arrays:

Part 1:
[[[ 1]
  [ 7]
  [13]]

 [[19]
  [25]
  [31]]

 [[37]
  [43]
  [49]]]
Shape: (3, 3, 1)

Part 2:
[[[ 2  3]
  [ 8  9]
  [14 15]]

 [[20 21]
  [26 27]
  [32 33]]

 [[38 39]
  [44 45]
  [50 51]]]
Shape: (3, 3, 2)

Part 3:
[[[ 4]
  [10]
  [16]]

 [[22]
  [28]
  [34]]

 [[40]
  [46]
  [52]]]
Shape: (3, 3, 1)

Part 4:
[[[ 5  6]
  [11 12]
  [17 18]]

 [[23 24]
  [29 30]
  [35 36]]

 [[41 42]
  [47 48]
  [53 54]]]
Shape: (3, 3, 2)


In [5]:
# Splitting a Multi-Color Image (Simulated RGB Layers)

# Simulate a 3D array representing an RGB image with shape 3x3x3
arr_rgb = np.array([[[255, 0, 0], [255, 0, 0], [255, 0, 0]], 
                    [[0, 255, 0], [0, 255, 0], [0, 255, 0]], 
                    [[0, 0, 255], [0, 0, 255], [0, 0, 255]]])
print("Input Array (RGB Layers):")
print(arr_rgb)
print("Shape:", arr_rgb.shape)

# Split the image into R, G, B layers
result = np.dsplit(arr_rgb, 3)
print("\nOutput Layers:")
for i, part in enumerate(result):
    print(f"Layer {i + 1}:\n{part}")
    print("Shape:", part.shape)

Input Array (RGB Layers):
[[[255   0   0]
  [255   0   0]
  [255   0   0]]

 [[  0 255   0]
  [  0 255   0]
  [  0 255   0]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]]]
Shape: (3, 3, 3)

Output Layers:
Layer 1:
[[[255]
  [255]
  [255]]

 [[  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]]]
Shape: (3, 3, 1)
Layer 2:
[[[  0]
  [  0]
  [  0]]

 [[255]
  [255]
  [255]]

 [[  0]
  [  0]
  [  0]]]
Shape: (3, 3, 1)
Layer 3:
[[[  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]]

 [[255]
  [255]
  [255]]]
Shape: (3, 3, 1)


In [7]:
# try to use dsplit() on a 2D array or lower

arr_2d = np.array([[1, 2, 3, 4, 5, 6],
                   [7, 8, 9, 10, 11, 12]])
print("Input Array (2D):")
print(arr_2d)
print("Shape:", arr_2d.shape)

# Attempt to split
try:
    result = np.dsplit(arr_2d, 3)
except ValueError as e:
    print("\nError:", e)


Input Array (2D):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Shape: (2, 6)

Error: dsplit only works on arrays of 3 or more dimensions


In [8]:
# Basic Unstacking Along the First Axis (axis=0)

import numpy as np

# Create a 3D array
arr = np.arange(24).reshape((2, 3, 4))
print("Input Array:")
print(arr)
print("Shape:", arr.shape)

# Unstack along the first axis (axis=0)
result = np.unstack(arr, axis=0)
print("\nresult:\n",result)

print("\nUnstacked Result (along axis=0):")
for i, part in enumerate(result):
    print(f"\nPart {i + 1}:\n{part}")
    print("Shape:", part.shape)


Input Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)

result:
 (array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]]))

Unstacked Result (along axis=0):

Part 1:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)

Part 2:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Shape: (3, 4)


In [9]:
type(result)

tuple

In [10]:
# Unstacking Along the Second Axis (axis=1)

print("Input Array:")
print(arr)
print("Shape:", arr.shape)

result = np.unstack(arr, axis=1)
print("\nresult:\n",result)
print("\nUnstacked Result (along axis=1):")
for i, part in enumerate(result):
    print(f"\nPart {i + 1}:\n{part}")
    print("Shape:", part.shape)

Input Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)

result:
 (array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]]))

Unstacked Result (along axis=1):

Part 1:
[[ 0  1  2  3]
 [12 13 14 15]]
Shape: (2, 4)

Part 2:
[[ 4  5  6  7]
 [16 17 18 19]]
Shape: (2, 4)

Part 3:
[[ 8  9 10 11]
 [20 21 22 23]]
Shape: (2, 4)


In [11]:
# Unstack along the depth axis (axis=2)

print("Input Array:")
print(arr)
print("Shape:", arr.shape)

result = np.unstack(arr, axis=2)
print("\nresult:\n",result)

print("\nUnstacked Result (along axis=2):")
for i, part in enumerate(result):
    print(f"\nPart {i + 1}:\n{part}")
    print("Shape:", part.shape)

Input Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)

result:
 (array([[ 0,  4,  8],
       [12, 16, 20]]), array([[ 1,  5,  9],
       [13, 17, 21]]), array([[ 2,  6, 10],
       [14, 18, 22]]), array([[ 3,  7, 11],
       [15, 19, 23]]))

Unstacked Result (along axis=2):

Part 1:
[[ 0  4  8]
 [12 16 20]]
Shape: (2, 3)

Part 2:
[[ 1  5  9]
 [13 17 21]]
Shape: (2, 3)

Part 3:
[[ 2  6 10]
 [14 18 22]]
Shape: (2, 3)

Part 4:
[[ 3  7 11]
 [15 19 23]]
Shape: (2, 3)


In [12]:
# Re-stacking After Unstacking

# Stack the unstacked result back along axis=2
arr_restacked = np.stack(result, axis=2)
print("\nRestacked Array (along axis=2):")
print(arr_restacked)
print("Shape:", arr_restacked.shape)

# Verify if the original array matches
print("\nAre the original and restacked arrays equal?\n",np.array_equal(arr, arr_restacked))



Restacked Array (along axis=2):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Shape: (2, 3, 4)

Are the original and restacked arrays equal?
 True


In [13]:
# Unstacking a 2D Array Along Columns (axis=1)

arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

print("Input 2D Array:")
print(arr_2d)
print("Shape:", arr_2d.shape)

# Unstack along the columns
result = np.unstack(arr_2d, axis=1)
print("\nUnstacked Result (along axis=1):")
for i, part in enumerate(result):
    print(f"\nColumn {i + 1}:\n{part}")
    print("Shape:", part.shape)

Input 2D Array:
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)

Unstacked Result (along axis=1):

Column 1:
[1 5]
Shape: (2,)

Column 2:
[2 6]
Shape: (2,)

Column 3:
[3 7]
Shape: (2,)

Column 4:
[4 8]
Shape: (2,)
