In [1]:
import numpy as np

In [2]:
# Creating a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

In [3]:
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
print(arr)

[1 2 3 4 5 6]


In [5]:
print(list(arr))

[1, 2, 3, 4, 5, 6]


# numpy.ravel(a, order='C')

In [8]:
# Create a 2D array
arr = np.array([[1, 2], [3, 4], [5, 6]])

# Reshape it into a 1D array (flatten it)
flattened_arr = arr.reshape(-1)

print("Original 2D Array:")
print(arr)
print("\n\nFlattened Array:")
print(flattened_arr)

Original 2D Array:
[[1 2]
 [3 4]
 [5 6]]


Flattened Array:
[1 2 3 4 5 6]


# numpy.ravel(a, order='C')


In [9]:
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr,"\n\n")

# Flatten the array using ravel()
flattened = np.ravel(arr)

print(flattened)

[[1 2 3]
 [4 5 6]] 


[1 2 3 4 5 6]


In [10]:
# Flatten the array column-wise using ravel()
flattened_f = np.ravel(arr, order='F')
print(flattened_f)


[1 4 2 5 3 6]


In [11]:
# Using 'A' and 'K' orders
flattened_a = np.ravel(arr, order='A')
flattened_k = np.ravel(arr, order='K')

print(flattened_a)
print(flattened_k)


[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [12]:
# Creating a transposed array
arr_transposed = arr.T
arr_transposed

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
# Flattening the transposed array -- C F A K
flattened_transposed = np.ravel(arr_transposed, order='K')
print(flattened_transposed)

[1 2 3 4 5 6]


# numpy.ndarray.flat


In [19]:
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr,"\n\n")
# Using ndarray.flat to iterate over the array elements
for element in arr.flat:
    print(element)


[[1 2 3]
 [4 5 6]] 


1
2
3
4
5
6


In [20]:
# Accessing the third element using flat (zero-based indexing)
third_element = arr.flat[2]
print(third_element)


3


In [21]:
# Modifying elements using flat
arr.flat[2] = 10
print(arr)


[[ 1  2 10]
 [ 4  5  6]]


In [23]:
# Using flat to multiply each element by 2
for i in range(arr.size):
    arr.flat[i] *= 2

print(arr)


[[ 4  8 40]
 [16 20 24]]


In [24]:
# Converting the flat iterator to a list
flat_list = list(arr.flat)
print(flat_list)

# Converting to a NumPy array
flat_array = np.array(arr.flat)
print(flat_array)


[4, 8, 40, 16, 20, 24]
[ 4  8 40 16 20 24]


# numpy.ndarray.flatten(order='C')


In [27]:
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr,"\n\n")
# Flattening the array using flatten()
flattened = arr.flatten()
print(flattened)


[[1 2 3]
 [4 5 6]] 


[1 2 3 4 5 6]


In [28]:
# Flatten the array column-wise using flatten()
flattened_f = arr.flatten(order='F')
print(flattened_f)


[1 4 2 5 3 6]


In [29]:
# Using 'A' and 'K' orders
flattened_a = arr.flatten(order='A')
flattened_k = arr.flatten(order='K')

print(flattened_a)
print(flattened_k)


[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [30]:
# Creating a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Flattening the 3D array
flattened_3d = arr_3d.flatten()
print(flattened_3d)


[1 2 3 4 5 6 7 8]


In [31]:
# Modifying the flattened array
flattened[2] = 10

print(flattened,"\n\n")

print(arr)

[ 1  2 10  4  5  6] 


[[1 2 3]
 [4 5 6]]
