# numpy.array_split(ary, indices_or_sections, axis=0)

In [1]:
import numpy as np

# Create an array of 9 numbers
ary = np.arange(9)

print("Input array before split_array:\n", ary)

# Split the array into 3 parts
split_array = np.array_split(ary, 3)

print("\nOutput after split_array:\n",split_array)


# Create an array of 9 numbers
ary = np.arange(10)

print("\nInput array before split_array:\n", ary)

# Split the array into 3 parts
split_array = np.array_split(ary, 3)

print("\nOutput after split_array:\n",split_array)


Input array before split_array:
 [0 1 2 3 4 5 6 7 8]

Output after split_array:
 [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

Input array before split_array:
 [0 1 2 3 4 5 6 7 8 9]

Output after split_array:
 [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [2]:
import numpy as np

# Create an array of 10 numbers
ary = np.arange(10)

print("Input array before split:\n", ary)

# Split the array into 3 parts
split_array = np.split(ary, 3)

print("\nOutput after split:\n",split_array)


Input array before split:
 [0 1 2 3 4 5 6 7 8 9]


ValueError: array split does not result in an equal division

In [4]:
import numpy as np

# Create an array of 9 numbers
ary = np.arange(12)

print("Input array before split:\n", ary)

# Split the array into 3 parts
split_array = np.split(ary, 4)

print("\nOutput after split:\n",split_array)


Input array before split:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Output after split:
 [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


In [5]:
# Split the array at specific indices

ary = np.arange(10)
split_array = np.array_split(ary, [3, 6])

print(split_array)


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]


In [6]:
# Split the array at specific indices

split_array = np.split(ary, [2, 5])

print(split_array)


[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]


In [11]:
import numpy as np
ary = np.arange(12).reshape(3, 4)

print("Input array:\n",ary)

# Split a 2D array along axis 0 (rows)
split_rows = np.split(ary, 3, axis=0)

# Split a 2D array along axis 1 (columns)
split_cols = np.split(ary, 2, axis=1)

print("\nRows split:\n", split_rows)
print("\nColumns split:\n", split_cols)


Input array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Rows split:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

Columns split:
 [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [12]:
import numpy as np
ary = np.arange(12).reshape(3, 4)

# Original array
print("Original Array:")
print(ary)
print("Shape of original array:", ary.shape)
print()

# Split along rows (axis=0)
split_rows = np.split(ary, 3, axis=0)

print("\nsplit_rows:\n",split_rows)
print("\nSplit along rows (axis=0):")
for i, row in enumerate(split_rows):
    print(f"Sub-array {i}:")
    print(row)
    print("Shape:", row.shape)
    print()

# Split along columns (axis=1)
split_cols = np.split(ary, 2, axis=1)

print("\nsplit_cols:\n",split_cols)
print("\nSplit along columns (axis=1):")
for i, col in enumerate(split_cols):
    print(f"Sub-array {i}:")
    print(col)
    print("Shape:", col.shape)
    print()


Original Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape of original array: (3, 4)


split_rows:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

Split along rows (axis=0):
Sub-array 0:
[[0 1 2 3]]
Shape: (1, 4)

Sub-array 1:
[[4 5 6 7]]
Shape: (1, 4)

Sub-array 2:
[[ 8  9 10 11]]
Shape: (1, 4)


split_cols:
 [array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]

Split along columns (axis=1):
Sub-array 0:
[[0 1]
 [4 5]
 [8 9]]
Shape: (3, 2)

Sub-array 1:
[[ 2  3]
 [ 6  7]
 [10 11]]
Shape: (3, 2)

