In [4]:
# Checking if All Elements are Non-Zero

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

result = np.all(arr)  # Checks if all elements are non-zero

print(result)

# Ensures that no elements are 0 before performing computations.

True


In [5]:
# Used in data validation to ensure all values meet a condition

arr = np.array([[1, 2, 3], [0, 5, 6], [7, 8, 9]])
print(arr)

result = np.all(arr > 5, axis=1)  # Check for each row
print(result)

[[1 2 3]
 [0 5 6]
 [7 8 9]]
[False False  True]


In [8]:
# Checking If All Values in a Masked Selection Satisfy a Condition

arr = np.array([2,5, 10, 15, 20, 25])
mask = arr > 10  # Select only elements greater than 10

result = np.all(arr % 5 == 0, where=mask)
print(result)

# Used in conditional filtering

True


In [9]:
# Checking If All Elements in Each Column Are Non-Zero

arr = np.array([[1, 0, 3], [4, 3, 6], [7, 8, 9]])
print(arr)

result = np.all(arr != 0, axis=0)  # Check column-wise
print(result)

[[1 0 3]
 [4 3 6]
 [7 8 9]]
[ True False  True]


In [13]:
# Keeping Dimensions Using keepdims=True

arr = np.array([[[1, 1, 1], [0, 1, 1]]])
print(arr, "\n")

result = np.all(arr, axis=1, keepdims=True)
print(result)

[[[1 1 1]
  [0 1 1]]] 

[[[False  True  True]]]


In [16]:
# Checking if Any Element is Non-Zero

import numpy as np

arr = np.array([0, 0, 7, 0, 0])
result = np.any(arr)  # Checks if any element is non-zero

print(result)

True


In [17]:
# Checking If Any Row Contains a Negative Value

arr = np.array([[1, 2, 3], [-1, 5, 6], [7, 8, 9]])
print(arr, "\n")

result = np.any(arr < 0, axis=1)  # Check for each row
print(result)

# Used in data validation to detect negative values

[[ 1  2  3]
 [-1  5  6]
 [ 7  8  9]] 

[False  True False]


In [19]:
# Checking If Any Value in a Masked Selection Is Positive

arr = np.array([-5, -10, 15, -20, -25])
mask = arr > 0  # Select only elements greater than 0

result = np.any(arr % 5 == 0, where=mask)
print(result)

# Used in conditional filtering

True


In [20]:
# The axis parameter specifies the dimension along which any() operates.

arr = np.array([[1, -2, 3], [4, 5, 6], [-7, 8, 9]])
print(arr, "\n")

result = np.any(arr < 0, axis=0)  # Check column-wise
print(result)

# Used in data quality checks

[[ 1 -2  3]
 [ 4  5  6]
 [-7  8  9]] 

[ True  True False]


In [21]:
# Keeping Dimensions Using keepdims=True

arr = np.array([[0, 1, 0], [0, 0, 0]])
print(arr, "\n")

result = np.any(arr, axis=1, keepdims=True)
print(result)

# Used in broadcasting and reshaping arrays

[[0 1 0]
 [0 0 0]] 

[[ True]
 [False]]
