# numpy.vstack(tup, dtype=None, casting='same_kind')

In [1]:
# Stacking 1D arrays

import numpy as np

# Two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking them vertically
result = np.vstack((a, b))

print(result)

[[1 2 3]
 [4 5 6]]


In [4]:
# Vertical Stacking of 2D Arrays

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(arr1,"\n\n")
print(arr2,"\n\n")


result = np.vstack((arr1, arr2))


print(result)


[[1 2]
 [3 4]] 


[[5 6]
 [7 8]] 


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
# Vertical Stacking of 2D Arrays

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])


result = np.vstack((arr1, arr2))
print(result)


[[1 2]
 [3 4]
 [5 6]]


In [6]:
# Mismatched Shapes

import numpy as np

# Mismatched 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7]])

print(a,"\n\n")
print(b,"\n\n")

# Attempting to stack them

result = np.vstack((a, b))

[[1 2]
 [3 4]] 


[[5 6 7]] 




ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [9]:
# Handling Different Data Types Using dtype

arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.array([4.5, 5.5, 6.5], dtype=np.float64)

result = np.vstack((arr1, arr2), dtype = np.int32, casting = 'unsafe')
print(result,"\n\n")

# print(list(result))

[[1 2 3]
 [4 5 6]] 




In [12]:
import numpy as np

# Two arrays with integers
a = np.array([1, 2, 3])
b = np.array([4.2, 5.6, 6.3])

# Stacking them with dtype as float
result = np.vstack((a, b), dtype=int, casting='unsafe')
print(result)


[[1 2 3]
 [4 5 6]]


# Key Points to Remember:

# The arrays must have the same number of columns for vstack() to work.

# numpy.hstack(tup, dtype=None, casting='same_kind')


In [13]:
# Stacking 1D Arrays

import numpy as np

# Two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking them horizontally
result = np.hstack((a, b))
print(result)


[1 2 3 4 5 6]


In [14]:
# Stacking 2D Arrays

# Two 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stacking them horizontally
result = np.hstack((a, b))
print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [15]:
# Mismatched Shapes


# Two arrays with different row sizes
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7]])

# Attempt to stack them horizontally
result = np.hstack((a, b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [18]:
# Mismatched Shapes


# Two arrays with different row sizes
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7],[8,9,10]])

# Attempt to stack them horizontally
result = np.hstack((a, b))

print(result)

[[ 1  2  5  6  7]
 [ 3  4  8  9 10]]


In [19]:
# Stacking Arrays with Different Shapes

arr1 = np.array([[1, 2]])
arr2 = np.array([[3, 4], [5, 6]])

result = np.hstack((arr1, arr2))
print(result)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

# Key Points to Remember:

# The arrays must have the same number of rows for hstack() to work.