# numpy.dstack(tup)

In [4]:
# Basic 2D Arrays Stacked Depth-Wise

import numpy as np

# Two 2D arrays (matrices)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Print input arrays and their shapes
print("Array a:\n", a)
print("Shape of a:", a.shape)

print("Array b:\n", b)
print("Shape of b:", b.shape)

# Stack depth-wise
result = np.dstack((a, b))

# Print the result and its shape
print("\nResult after dstack:\n", result)
print("Shape of result:", result.shape)

Array a:
 [[1 2]
 [3 4]]
Shape of a: (2, 2)
Array b:
 [[5 6]
 [7 8]]
Shape of b: (2, 2)

Result after dstack:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of result: (2, 2, 2)


In [5]:
# Stacking 1D Arrays

import numpy as np

# Two 1D arrays
a = np.array([1, 2])
b = np.array([3, 4])

# Print input arrays and their shapes
print("Array a:\n", a)
print("Shape of a:", a.shape)

print("Array b:\n", b)
print("Shape of b:", b.shape)

# Stack depth-wise
result = np.dstack((a, b))

# Print the result and its shape
print("\nResult after dstack:\n", result)
print("Shape of result:", result.shape)


Array a:
 [1 2]
Shape of a: (2,)
Array b:
 [3 4]
Shape of b: (2,)

Result after dstack:
 [[[1 3]
  [2 4]]]
Shape of result: (1, 2, 2)


In [6]:
# Stacking 3D Arrays

import numpy as np

# Two 3D arrays
a = np.array([[[1], [2]], [[3], [4]]])  # Shape (2, 2, 1)
b = np.array([[[5], [6]], [[7], [8]]])  # Shape (2, 2, 1)

# Print input arrays and their shapes
print("Array a:\n", a)
print("Shape of a:", a.shape)

print("Array b:\n", b)
print("Shape of b:", b.shape)

# Stack depth-wise
result = np.dstack((a, b))

# Print the result and its shape
print("\nResult after dstack:\n", result)
print("Shape of result:", result.shape)


Array a:
 [[[1]
  [2]]

 [[3]
  [4]]]
Shape of a: (2, 2, 1)
Array b:
 [[[5]
  [6]]

 [[7]
  [8]]]
Shape of b: (2, 2, 1)

Result after dstack:
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of result: (2, 2, 2)


In [7]:
# Combining Multiple Arrays

import numpy as np

# Three 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])

# Print input arrays and their shapes
print("Array a:\n", a)
print("Shape of a:", a.shape)

print("Array b:\n", b)
print("Shape of b:", b.shape)

print("Array c:\n", c)
print("Shape of c:", c.shape)

# Stack depth-wise
result = np.dstack((a, b, c))

# Print the result and its shape
print("\nResult after dstack:\n", result)
print("Shape of result:", result.shape)

Array a:
 [[1 2]
 [3 4]]
Shape of a: (2, 2)
Array b:
 [[5 6]
 [7 8]]
Shape of b: (2, 2)
Array c:
 [[ 9 10]
 [11 12]]
Shape of c: (2, 2)

Result after dstack:
 [[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]]
Shape of result: (2, 2, 3)


In [8]:
# depth Stacking empty Arrays

import numpy as np

# Two 3D arrays
a = np.array([])
b = np.array([])

# Print input arrays and their shapes
print("Array a:\n", a)
print("Shape of a:", a.shape)

print("Array b:\n", b)
print("Shape of b:", b.shape)

# Stack depth-wise
result = np.dstack((a, b))

# Print the result and its shape
print("\nResult after dstack:\n", result)
print("Shape of result:", result.shape)

Array a:
 []
Shape of a: (0,)
Array b:
 []
Shape of b: (0,)

Result after dstack:
 []
Shape of result: (1, 0, 2)


# Important Points to Note:
The dstack function promotes lower-dimensional arrays to higher dimensions when necessary.

The number of rows and columns of the input arrays must match, but the depth axis can be stacked freely.

The function is especially useful when dealing with multi-dimensional data, such as RGB image data (where you stack the color channels).

# Use Cases:
Image Processing: dstack() can be used to combine different color channels (R, G, B) into a single 3D array, where the third axis represents different channels.

3D Data Visualization: It's useful for visualizing and manipulating data in 3D space, stacking layers of 2D data.

Scientific Computing: When dealing with multi-dimensional data (e.g., 3D grids), dstack() helps in combining different planes into one structure.

# numpy.column_stack(tup)


In [10]:
# Stacking 1D Arrays into Columns

import numpy as np

# Two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Print input arrays and their shapes
print("Array a:\n", a)
print("Shape of a:", a.shape)

print("Array b:\n", b)
print("Shape of b:", b.shape)

# Stack as columns
result = np.column_stack((a, b))

# Print the result and its shape
print("\nResult after column_stack:\n", result)
print("Shape of result:", result.shape)


Array a:
 [1 2 3]
Shape of a: (3,)
Array b:
 [4 5 6]
Shape of b: (3,)

Result after column_stack:
 [[1 4]
 [2 5]
 [3 6]]
Shape of result: (3, 2)


In [16]:
# Stacking Multiple 1D Arrays

import numpy as np

# Three 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# Print input arrays and their shapes
print("Array a:\n", a)
print("Shape of a:", a.shape)

print("Array b:\n", b)
print("Shape of b:", b.shape)

print("Array c:\n", c)
print("Shape of c:", c.shape)

# Stack as columns
result = np.column_stack((a, b, c))

# Print the result and its shape
print("\nResult after column_stack:\n", result)
print("Shape of result:", result.shape)


Array a:
 [1 2 3]
Shape of a: (3,)
Array b:
 [4 5 6]
Shape of b: (3,)
Array c:
 [7 8 9]
Shape of c: (3,)

Result after column_stack:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Shape of result: (3, 3)


In [12]:
# Stacking 2D Arrays

import numpy as np

# Two 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Print input arrays and their shapes
print("Array a:\n", a)
print("Shape of a:", a.shape)

print("Array b:\n", b)
print("Shape of b:", b.shape)

# Stack as columns
result = np.column_stack((a, b))

# Print the result and its shape
print("\nResult after column_stack:\n", result)
print("Shape of result:", result.shape)


Array a:
 [[1 2]
 [3 4]]
Shape of a: (2, 2)
Array b:
 [[5 6]
 [7 8]]
Shape of b: (2, 2)

Result after column_stack:
 [[1 2 5 6]
 [3 4 7 8]]
Shape of result: (2, 4)


In [13]:
# Stacking Arrays of Different Dimensions

import numpy as np

# One 1D array and one 2D array
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])

# Print input arrays and their shapes
print("Array a:\n", a)
print("Shape of a:", a.shape)

print("Array b:\n", b)
print("Shape of b:", b.shape)

# Stack as columns
result = np.column_stack((a, b.T))  # Using transpose (b.T) to match dimensions

# Print the result and its shape
print("\nResult after column_stack:\n", result)
print("Shape of result:", result.shape)


Array a:
 [1 2 3]
Shape of a: (3,)
Array b:
 [[4 5 6]
 [7 8 9]]
Shape of b: (2, 3)

Result after column_stack:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Shape of result: (3, 3)


In [14]:
# Edge Case with Zero-Length Arrays

import numpy as np

# Two empty 1D arrays
a = np.array([])
b = np.array([])

# Print input arrays and their shapes
print("Array a:\n", a)
print("Shape of a:", a.shape)

print("Array b:\n", b)
print("Shape of b:", b.shape)

# Stack as columns
result = np.column_stack((a, b))

# Print the result and its shape
print("\nResult after column_stack:\n", result)
print("Shape of result:", result.shape)


Array a:
 []
Shape of a: (0,)
Array b:
 []
Shape of b: (0,)

Result after column_stack:
 []
Shape of result: (0, 2)


# Important Points to Note:

Shape Compatibility: All input arrays must have the same length (number of elements) along the first axis. Otherwise, column_stack() will raise an error.

Promotion to 2D: If 1D arrays are passed, they are automatically promoted to 2D (with one column per array).

# Use Cases:

Data Preparation: column_stack() is very useful when preparing data matrices from individual feature columns (1D arrays) for machine learning tasks.
    
Merging Data: It helps combine separate arrays representing different variables into a single 2D array for further analysis.
    
Scientific Computation: In scientific applications, column_stack() is often used to combine different measurements into a data matrix.